######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 13 11:08:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

RESOURCES += \
    hidpi.qrc

